# Generated by Django 2.2.4 on 2019-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricaoProduto', models.TextField()),
                ('unidadeCompra', models.CharField(max_length=50)),
                ('qtdPrevistoMes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precoMaximo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
